### ISSUE TITLE
sessionInfo

### ISSUE THREAD

**Issue by zx8754** [schochastics/minard#1]
Could you add output of `sessionInfo()`, I can't reproduce the code. Failing at [L62:](https://github.com/schochastics/minard/blob/master/napoleon.R#L62)

```R
p <- p1+p2+ plot_layout(ncol = 1, heights = c(3, 1))+
```

> Error: Don't know how to add o to a plot

**Comment by schochastics** [comment]
Added the session info to the readme. The error looks like you do not have the [patchwork package](https://github.com/thomasp85/patchwork) installed: `devtools::install_github("thomasp85/patchwork")`

**Comment by zx8754** [comment]
@schochastics Yes, R needed to be restarted after installing `patchwork`. All works, thank you, closing.
